apiVersion: v2
name: homelab
description: kevin's homelab
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  - name: graphite
    version: 1.1.0
    repository: https://kiwigrid.github.io
  - name: postgresql
    version: 0.2.5
    repository: https://cetic.github.io/helm-charts 
  - name: adminer
    version: 0.2.1
    repository: https://cetic.github.io/helm-charts 
  - name: open-webui
    repository: https://helm.openwebui.com
    version: 5.20.0
  - name: rabbitmq
    repository: https://charts.bitnami.com/bitnami
    version: 16.0.8
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 74.2.1
